# Generated by Django 5.1.1 on 2024-11-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoEscaneado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('qr_image', models.ImageField(blank=True, upload_to='codigo_qr/')),
            ],
        ),
    ]
