# Generated by Django 5.1.1 on 2024-10-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('qr_image', models.ImageField(blank=True, upload_to='qr_codes/')),
            ],
        ),
    ]
