# Generated by Django 5.1.1 on 2024-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo_qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='codigo_qr/'),
        ),
    ]
