# Generated by Django 5.1.1 on 2024-10-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo_qr', '0002_alter_codigoqr_qr_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoEscaneado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
