# Generated by Django 5.1.1 on 2024-11-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_1', models.CharField(max_length=50)),
                ('apellido_2', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_contratacion', models.DateField()),
                ('cumpleaños', models.DateField()),
                ('is_on_leave', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='codigo_qr/')),
            ],
        ),
        migrations.CreateModel(
            name='RolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('CEO', 'CEO'), ('CTO', 'CTO'), ('CFO', 'CFO'), ('LÍDER_DESARROLLO', 'Líder de Equipo de Desarrollo'), ('INGENIERO_FRONTEND', 'Ingeniero de Frontend'), ('INGENIERO_BACKEND', 'Ingeniero de Backend'), ('LÍDER_QA', 'Líder de QA'), ('INGENIERO_QA', 'Ingeniero de QA'), ('GERENTE_PROYECTO', 'Gerente de Proyecto'), ('COORDINADOR_PROYECTO', 'Coordinador de Proyecto'), ('GERENTE_PRODUCTO', 'Gerente de Producto'), ('PROPIETARIO_PRODUCTO', 'Propietario de Producto'), ('GERENTE_MARKETING', 'Gerente de Marketing'), ('ESPECIALISTA_MARKETING', 'Especialista en Marketing Digital'), ('GERENTE_VENTAS', 'Gerente de Ventas'), ('REPRESENTANTE_VENTAS', 'Representante de Ventas'), ('GERENTE_SOPORTE', 'Gerente de Soporte'), ('ESPECIALISTA_SOPORTE', 'Especialista en Soporte al Cliente')], max_length=50)),
            ],
        ),
    ]
