# Generated by Django 5.1.1 on 2024-10-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_empleado_puesto_empleado_rol_empleado_sede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='codigo_qr/'),
        ),
    ]
