# Generated by Django 5.1.1 on 2024-10-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_empleado_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='cumpleaños',
            new_name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='empleado',
            name='qr_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
