# Generated by Django 5.0.6 on 2024-10-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_cumpleaños_empleado_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='fecha_nacimiento',
            new_name='cumpleaños',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='qr_token',
        ),
    ]
